# Install as docker-compose-infisical@month-planner.service.d/override.conf.
[Service]
Type=oneshot
RemainAfterExit=yes
Restart=no
ExecStartPre=
ExecStartPre=/home/honya/.local/libexec/infisical-render month-planner
ExecStart=
ExecStart=/usr/bin/true
ExecStop=
